template = "https://github.com/giellalt/template-lang-und"
rev_id = 292
template_sha = "ae713c1306873a265055417badc511956629639d"

[replacements]
__GLOTTOLOG_ID__ = "roma1327"
__REPO__ = "lang-ron"
__UND2C__ = "ro"
__UNDEFINED__ = "Romanian"
__UND__ = "ron"
