template = "https://github.com/giellalt/template-lang-und"
rev_id = 302
template_sha = "b3740681672fe3b348eb75d3170f7a2da900a0b1"

[replacements]
__GLOTTOLOG_ID__ = "roma1327"
__REPO__ = "lang-ron"
__UND2C__ = "ro"
__UNDEFINED__ = "Romanian"
__UND__ = "ron"
