template = "https://github.com/giellalt/template-lang-und"
rev_id = 337
template_sha = "1c2fffaa917a9c6f340d9887d554609eb561ade6"

[replacements]
__GLOTTOLOG_ID__ = "roma1327"
__REPO__ = "lang-ron"
__UND2C__ = "ro"
__UNDEFINED__ = "Romanian"
__UND__ = "ron"
