[package]
name = "ron"
human_name = "Romanian"
version = "0.1.0"

# Table of speller tag -> filename to include in the bundle
# filenames depends on specific project
[spellers.ron]
filename = "ro-mobile.zhfst"

# Table of bundles to generated
# key is the type of bundle
# Windows speller bundle require a uuid for the installer
[bundles.speller_win]
package = "speller-ron"
platform = "windows"
uuid = "745D2420-FB19-4BD7-8AD8-A1979B024F25"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_macos]
pkg_id = "no.divvun.MacDivvun.ro"
package = "speller-ron"
platform = "macos"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_win_mso]
package = "speller-ron-mso"
platform = "windows"
uuid = "7000C4ED-60C8-4B2E-A4D8-AA8EAAFE5858"
repo = "https://pahkat.uit.no/main/"

[bundles.speller_mobile]
package = "speller-ron"
platform = "mobile"
repo = "https://pahkat.uit.no/main/"
